#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
spring.application.name=EWSDSpringWeb
server.port=8080


#Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.sa-east-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=4MJZEgZFMYXYNVN.root
spring.datasource.password=CjzAP2X633wW01dn

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


